# Generated by Django 5.1.6 on 2025-03-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_alter_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='verificationresult',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='verificationresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='verification_images/'),
        ),
    ]
